#!/bin/bash
BUILDDIR=build_osx_10.8
[ ! -d $BUILDDIR ] && mkdir $BUILDDIR
cd $BUILDDIR
cmake -DSYSTEM_OPENSSL=ON -DSYSTEM_BOOST=OFF -DCRASH_REPORTING=ON -DLOGGING=ON -DTARGET_ARCH="x86_64" -DCMAKE_OSX_ARCHITECTURES="x86_64" -DCMAKE_OSX_DEPLOYMENT_TARGET="10.8" -G"Xcode" ..
